In [18]:
import numpy as np,pandas as pd,matplotlib.pyplot as plt,sklearn as sk,seaborn as sns

In [43]:
df=pd.read_csv('/Users/sameersangam/Desktop/Kaggle/Titanic/train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [44]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [45]:
df.drop(['PassengerId','Name','Ticket','Fare','Cabin'],inplace=True,axis=1)

In [47]:
dict1={'male':0,'female':'1'}
dict2={'C':0,'S':1,'Q':2}
df.replace({'Sex':dict1,'Embarked':dict2},inplace=True)
df

Survived  Pclass Sex   Age  SibSp  Parch  Embarked
0           0       3   0  22.0      1      0       1.0
1           1       1   1  38.0      1      0       0.0
2           1       3   1  26.0      0      0       1.0
3           1       1   1  35.0      1      0       1.0
4           0       3   0  35.0      0      0       1.0
..        ...     ...  ..   ...    ...    ...       ...
886         0       2   0  27.0      0      0       1.0
887         1       1   1  19.0      0      0       1.0
888         0       3   1   NaN      1      2       1.0
889         1       1   0  26.0      0      0       0.0
890         0       3   0  32.0      0      0       2.0

[891 rows x 7 columns]

In [48]:
y=df.iloc[:,0].values
X=df.iloc[:,1:].values
X

array([[3, 0, 22.0, 1, 0, 1.0],
       [1, '1', 38.0, 1, 0, 0.0],
       [3, '1', 26.0, 0, 0, 1.0],
       ...,
       [3, '1', nan, 1, 2, 1.0],
       [1, 0, 26.0, 0, 0, 0.0],
       [3, 0, 32.0, 0, 0, 2.0]], dtype=object)

In [50]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(weights='distance',n_neighbors=5)
X=imputer.fit_transform(X)
X

array([[ 3. ,  0. , 22. ,  1. ,  0. ,  1. ],
       [ 1. ,  1. , 38. ,  1. ,  0. ,  0. ],
       [ 3. ,  1. , 26. ,  0. ,  0. ,  1. ],
       ...,
       [ 3. ,  1. , 24.8,  1. ,  2. ,  1. ],
       [ 1. ,  0. , 26. ,  0. ,  0. ,  0. ],
       [ 3. ,  0. , 32. ,  0. ,  0. ,  2. ]])

In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)


In [52]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8022388059701493

In [62]:
df1=pd.read_csv('test.csv')
df1

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [54]:
df1.drop(['PassengerId','Name','Ticket','Fare','Cabin'],inplace=True,axis=1)

In [55]:
df1

Pclass     Sex   Age  SibSp  Parch Embarked
0         3    male  34.5      0      0        Q
1         3  female  47.0      1      0        S
2         2    male  62.0      0      0        Q
3         3    male  27.0      0      0        S
4         3  female  22.0      1      1        S
..      ...     ...   ...    ...    ...      ...
413       3    male   NaN      0      0        S
414       1  female  39.0      0      0        C
415       3    male  38.5      0      0        S
416       3    male   NaN      0      0        S
417       3    male   NaN      1      1        C

[418 rows x 6 columns]

In [56]:
dict1={'male':0,'female':'1'}
dict2={'C':0,'S':1,'Q':2}
df1.replace({'Sex':dict1,'Embarked':dict2},inplace=True)
df1

Pclass Sex   Age  SibSp  Parch  Embarked
0         3   0  34.5      0      0         2
1         3   1  47.0      1      0         1
2         2   0  62.0      0      0         2
3         3   0  27.0      0      0         1
4         3   1  22.0      1      1         1
..      ...  ..   ...    ...    ...       ...
413       3   0   NaN      0      0         1
414       1   1  39.0      0      0         0
415       3   0  38.5      0      0         1
416       3   0   NaN      0      0         1
417       3   0   NaN      1      1         0

[418 rows x 6 columns]

In [57]:
X_test1=df1.iloc[:,:].values

In [59]:
X_test1=imputer.fit_transform(X_test1)

In [60]:
X_test1

array([[ 3. ,  0. , 34.5,  0. ,  0. ,  2. ],
       [ 3. ,  1. , 47. ,  1. ,  0. ,  1. ],
       [ 2. ,  0. , 62. ,  0. ,  0. ,  2. ],
       ...,
       [ 3. ,  0. , 38.5,  0. ,  0. ,  1. ],
       [ 3. ,  0. , 25.1,  0. ,  0. ,  1. ],
       [ 3. ,  0. ,  6.5,  1. ,  1. ,  0. ]])

In [61]:
y_pred1=clf.predict(X_test1)
y_pred1

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,

In [64]:
df1.insert(1,"Survived",y_pred1,True)
df1

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         0       3   
2            894         0       2   
3            895         0       3   
4            896         0       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         1       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [67]:
df1.drop(df1.iloc[:,2:],axis=1,inplace=True)


In [73]:
df1

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]

In [74]:
df1.to_csv('submission.csv',index=False)